//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MVVM.ServiceReference1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class BasicHttpBinding_IService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PlayersOperationCompleted;
        
        private System.Threading.SendOrPostCallback IniciarOperationCompleted;
        
        private System.Threading.SendOrPostCallback LimpiarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarJuegoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getJuegoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarJuegoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaJuegoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BasicHttpBinding_IService1() {
            this.Url = global::MVVM.Properties.Settings.Default.MVVM_ServiceReference1_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PlayersCompletedEventHandler PlayersCompleted;
        
        /// <remarks/>
        public event IniciarCompletedEventHandler IniciarCompleted;
        
        /// <remarks/>
        public event LimpiarCompletedEventHandler LimpiarCompleted;
        
        /// <remarks/>
        public event ActualizarJuegoCompletedEventHandler ActualizarJuegoCompleted;
        
        /// <remarks/>
        public event getJuegoCompletedEventHandler getJuegoCompleted;
        
        /// <remarks/>
        public event EliminarJuegoCompletedEventHandler EliminarJuegoCompleted;
        
        /// <remarks/>
        public event ListaJuegoCompletedEventHandler ListaJuegoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Players", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfAzure2")]
        public Jugador[] Players() {
            object[] results = this.Invoke("Players", new object[0]);
            return ((Jugador[])(results[0]));
        }
        
        /// <remarks/>
        public void PlayersAsync() {
            this.PlayersAsync(null);
        }
        
        /// <remarks/>
        public void PlayersAsync(object userState) {
            if ((this.PlayersOperationCompleted == null)) {
                this.PlayersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPlayersOperationCompleted);
            }
            this.InvokeAsync("Players", new object[0], this.PlayersOperationCompleted, userState);
        }
        
        private void OnPlayersOperationCompleted(object arg) {
            if ((this.PlayersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PlayersCompleted(this, new PlayersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Iniciar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Juego Iniciar() {
            object[] results = this.Invoke("Iniciar", new object[0]);
            return ((Juego)(results[0]));
        }
        
        /// <remarks/>
        public void IniciarAsync() {
            this.IniciarAsync(null);
        }
        
        /// <remarks/>
        public void IniciarAsync(object userState) {
            if ((this.IniciarOperationCompleted == null)) {
                this.IniciarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciarOperationCompleted);
            }
            this.InvokeAsync("Iniciar", new object[0], this.IniciarOperationCompleted, userState);
        }
        
        private void OnIniciarOperationCompleted(object arg) {
            if ((this.IniciarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciarCompleted(this, new IniciarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Limpiar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Limpiar() {
            this.Invoke("Limpiar", new object[0]);
        }
        
        /// <remarks/>
        public void LimpiarAsync() {
            this.LimpiarAsync(null);
        }
        
        /// <remarks/>
        public void LimpiarAsync(object userState) {
            if ((this.LimpiarOperationCompleted == null)) {
                this.LimpiarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLimpiarOperationCompleted);
            }
            this.InvokeAsync("Limpiar", new object[0], this.LimpiarOperationCompleted, userState);
        }
        
        private void OnLimpiarOperationCompleted(object arg) {
            if ((this.LimpiarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LimpiarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ActualizarJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarJuego([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Juego game) {
            this.Invoke("ActualizarJuego", new object[] {
                        game});
        }
        
        /// <remarks/>
        public void ActualizarJuegoAsync(Juego game) {
            this.ActualizarJuegoAsync(game, null);
        }
        
        /// <remarks/>
        public void ActualizarJuegoAsync(Juego game, object userState) {
            if ((this.ActualizarJuegoOperationCompleted == null)) {
                this.ActualizarJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarJuegoOperationCompleted);
            }
            this.InvokeAsync("ActualizarJuego", new object[] {
                        game}, this.ActualizarJuegoOperationCompleted, userState);
        }
        
        private void OnActualizarJuegoOperationCompleted(object arg) {
            if ((this.ActualizarJuegoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarJuegoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/getJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Juego getJuego([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("getJuego", new object[] {
                        id});
            return ((Juego)(results[0]));
        }
        
        /// <remarks/>
        public void getJuegoAsync(string id) {
            this.getJuegoAsync(id, null);
        }
        
        /// <remarks/>
        public void getJuegoAsync(string id, object userState) {
            if ((this.getJuegoOperationCompleted == null)) {
                this.getJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetJuegoOperationCompleted);
            }
            this.InvokeAsync("getJuego", new object[] {
                        id}, this.getJuegoOperationCompleted, userState);
        }
        
        private void OngetJuegoOperationCompleted(object arg) {
            if ((this.getJuegoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getJuegoCompleted(this, new getJuegoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/EliminarJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarJuego([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Juego juego) {
            this.Invoke("EliminarJuego", new object[] {
                        juego});
        }
        
        /// <remarks/>
        public void EliminarJuegoAsync(Juego juego) {
            this.EliminarJuegoAsync(juego, null);
        }
        
        /// <remarks/>
        public void EliminarJuegoAsync(Juego juego, object userState) {
            if ((this.EliminarJuegoOperationCompleted == null)) {
                this.EliminarJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarJuegoOperationCompleted);
            }
            this.InvokeAsync("EliminarJuego", new object[] {
                        juego}, this.EliminarJuegoOperationCompleted, userState);
        }
        
        private void OnEliminarJuegoOperationCompleted(object arg) {
            if ((this.EliminarJuegoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarJuegoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListaJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfAzure2")]
        public Juego[] ListaJuego() {
            object[] results = this.Invoke("ListaJuego", new object[0]);
            return ((Juego[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaJuegoAsync() {
            this.ListaJuegoAsync(null);
        }
        
        /// <remarks/>
        public void ListaJuegoAsync(object userState) {
            if ((this.ListaJuegoOperationCompleted == null)) {
                this.ListaJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaJuegoOperationCompleted);
            }
            this.InvokeAsync("ListaJuego", new object[0], this.ListaJuegoOperationCompleted, userState);
        }
        
        private void OnListaJuegoOperationCompleted(object arg) {
            if ((this.ListaJuegoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaJuegoCompleted(this, new ListaJuegoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpsBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class BasicHttpsBinding_IService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PlayersOperationCompleted;
        
        private System.Threading.SendOrPostCallback IniciarOperationCompleted;
        
        private System.Threading.SendOrPostCallback LimpiarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarJuegoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getJuegoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarJuegoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaJuegoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BasicHttpsBinding_IService1() {
            this.Url = "https://wcfazure220200703020416multi.azurewebsites.net/Service1.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PlayersCompletedEventHandler PlayersCompleted;
        
        /// <remarks/>
        public event IniciarCompletedEventHandler IniciarCompleted;
        
        /// <remarks/>
        public event LimpiarCompletedEventHandler LimpiarCompleted;
        
        /// <remarks/>
        public event ActualizarJuegoCompletedEventHandler ActualizarJuegoCompleted;
        
        /// <remarks/>
        public event getJuegoCompletedEventHandler getJuegoCompleted;
        
        /// <remarks/>
        public event EliminarJuegoCompletedEventHandler EliminarJuegoCompleted;
        
        /// <remarks/>
        public event ListaJuegoCompletedEventHandler ListaJuegoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Players", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfAzure2")]
        public Jugador[] Players() {
            object[] results = this.Invoke("Players", new object[0]);
            return ((Jugador[])(results[0]));
        }
        
        /// <remarks/>
        public void PlayersAsync() {
            this.PlayersAsync(null);
        }
        
        /// <remarks/>
        public void PlayersAsync(object userState) {
            if ((this.PlayersOperationCompleted == null)) {
                this.PlayersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPlayersOperationCompleted);
            }
            this.InvokeAsync("Players", new object[0], this.PlayersOperationCompleted, userState);
        }
        
        private void OnPlayersOperationCompleted(object arg) {
            if ((this.PlayersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PlayersCompleted(this, new PlayersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Iniciar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Juego Iniciar() {
            object[] results = this.Invoke("Iniciar", new object[0]);
            return ((Juego)(results[0]));
        }
        
        /// <remarks/>
        public void IniciarAsync() {
            this.IniciarAsync(null);
        }
        
        /// <remarks/>
        public void IniciarAsync(object userState) {
            if ((this.IniciarOperationCompleted == null)) {
                this.IniciarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciarOperationCompleted);
            }
            this.InvokeAsync("Iniciar", new object[0], this.IniciarOperationCompleted, userState);
        }
        
        private void OnIniciarOperationCompleted(object arg) {
            if ((this.IniciarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciarCompleted(this, new IniciarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Limpiar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Limpiar() {
            this.Invoke("Limpiar", new object[0]);
        }
        
        /// <remarks/>
        public void LimpiarAsync() {
            this.LimpiarAsync(null);
        }
        
        /// <remarks/>
        public void LimpiarAsync(object userState) {
            if ((this.LimpiarOperationCompleted == null)) {
                this.LimpiarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLimpiarOperationCompleted);
            }
            this.InvokeAsync("Limpiar", new object[0], this.LimpiarOperationCompleted, userState);
        }
        
        private void OnLimpiarOperationCompleted(object arg) {
            if ((this.LimpiarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LimpiarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ActualizarJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarJuego([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Juego game) {
            this.Invoke("ActualizarJuego", new object[] {
                        game});
        }
        
        /// <remarks/>
        public void ActualizarJuegoAsync(Juego game) {
            this.ActualizarJuegoAsync(game, null);
        }
        
        /// <remarks/>
        public void ActualizarJuegoAsync(Juego game, object userState) {
            if ((this.ActualizarJuegoOperationCompleted == null)) {
                this.ActualizarJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarJuegoOperationCompleted);
            }
            this.InvokeAsync("ActualizarJuego", new object[] {
                        game}, this.ActualizarJuegoOperationCompleted, userState);
        }
        
        private void OnActualizarJuegoOperationCompleted(object arg) {
            if ((this.ActualizarJuegoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarJuegoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/getJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Juego getJuego([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("getJuego", new object[] {
                        id});
            return ((Juego)(results[0]));
        }
        
        /// <remarks/>
        public void getJuegoAsync(string id) {
            this.getJuegoAsync(id, null);
        }
        
        /// <remarks/>
        public void getJuegoAsync(string id, object userState) {
            if ((this.getJuegoOperationCompleted == null)) {
                this.getJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetJuegoOperationCompleted);
            }
            this.InvokeAsync("getJuego", new object[] {
                        id}, this.getJuegoOperationCompleted, userState);
        }
        
        private void OngetJuegoOperationCompleted(object arg) {
            if ((this.getJuegoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getJuegoCompleted(this, new getJuegoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/EliminarJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarJuego([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Juego juego) {
            this.Invoke("EliminarJuego", new object[] {
                        juego});
        }
        
        /// <remarks/>
        public void EliminarJuegoAsync(Juego juego) {
            this.EliminarJuegoAsync(juego, null);
        }
        
        /// <remarks/>
        public void EliminarJuegoAsync(Juego juego, object userState) {
            if ((this.EliminarJuegoOperationCompleted == null)) {
                this.EliminarJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarJuegoOperationCompleted);
            }
            this.InvokeAsync("EliminarJuego", new object[] {
                        juego}, this.EliminarJuegoOperationCompleted, userState);
        }
        
        private void OnEliminarJuegoOperationCompleted(object arg) {
            if ((this.EliminarJuegoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarJuegoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListaJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfAzure2")]
        public Juego[] ListaJuego() {
            object[] results = this.Invoke("ListaJuego", new object[0]);
            return ((Juego[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaJuegoAsync() {
            this.ListaJuegoAsync(null);
        }
        
        /// <remarks/>
        public void ListaJuegoAsync(object userState) {
            if ((this.ListaJuegoOperationCompleted == null)) {
                this.ListaJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaJuegoOperationCompleted);
            }
            this.InvokeAsync("ListaJuego", new object[0], this.ListaJuegoOperationCompleted, userState);
        }
        
        private void OnListaJuegoOperationCompleted(object arg) {
            if ((this.ListaJuegoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaJuegoCompleted(this, new ListaJuegoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfAzure2")]
    public partial class Jugador {
        
        private string colorField;
        
        private int footprintField;
        
        private bool footprintFieldSpecified;
        
        private bool statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public int Footprint {
            get {
                return this.footprintField;
            }
            set {
                this.footprintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FootprintSpecified {
            get {
                return this.footprintFieldSpecified;
            }
            set {
                this.footprintFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfAzure2")]
    public partial class Juego {
        
        private int[] contadoresField;
        
        private bool ganadorField;
        
        private bool ganadorFieldSpecified;
        
        private string idField;
        
        private Jugador jugadorAzulField;
        
        private Jugador jugadorRojoField;
        
        private int[] matrizField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public int[] Contadores {
            get {
                return this.contadoresField;
            }
            set {
                this.contadoresField = value;
            }
        }
        
        /// <remarks/>
        public bool Ganador {
            get {
                return this.ganadorField;
            }
            set {
                this.ganadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GanadorSpecified {
            get {
                return this.ganadorFieldSpecified;
            }
            set {
                this.ganadorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Jugador JugadorAzul {
            get {
                return this.jugadorAzulField;
            }
            set {
                this.jugadorAzulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Jugador JugadorRojo {
            get {
                return this.jugadorRojoField;
            }
            set {
                this.jugadorRojoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public int[] Matriz {
            get {
                return this.matrizField;
            }
            set {
                this.matrizField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PlayersCompletedEventHandler(object sender, PlayersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlayersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PlayersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Jugador[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Jugador[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IniciarCompletedEventHandler(object sender, IniciarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IniciarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IniciarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Juego Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Juego)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LimpiarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ActualizarJuegoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getJuegoCompletedEventHandler(object sender, getJuegoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getJuegoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getJuegoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Juego Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Juego)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarJuegoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListaJuegoCompletedEventHandler(object sender, ListaJuegoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaJuegoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaJuegoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Juego[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Juego[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591